language: php

php:
  - 7.1
  - 7.2

before_script:
  - phpenv config-rm xdebug.ini || true
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

script:
  - phpunit

notifications:
  email: false
